1. Hacer las importaciones necesarias para abrir un archivo de tipo csv en Pandas.

In [2]:
import pandas as pd

2. Abrir el archivo, creando un dataframe. Aseguraros de que no incluye la columna "Unnamed: 0".

In [3]:
videogames = pd.read_csv("./Ficheros/videogames.csv")
videogames_updated = videogames.drop(columns=["Unnamed: 0"])

videogames_updated

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20798,"Enjoy Your Power, Enjoy Your Choice",https://www.imdb.com/title/tt3845606/?ref_=adv...,2014.0,NaN,NaN,NaN,Add a Plot,False,False,False,False,False,False,False,False,True
20799,RedSun2020,https://www.imdb.com/title/tt0790739/?ref_=adv...,2004.0,NaN,NaN,NaN,Joseph gets kidnapped and it's the player's jo...,False,False,False,False,False,False,False,False,True
20800,Shutter,https://www.imdb.com/title/tt5119948/?ref_=adv...,2015.0,NaN,NaN,NaN,A tech support man who uses a drone to investi...,False,False,False,False,False,False,False,False,True
20801,The Music Machine,https://www.imdb.com/title/tt5142082/?ref_=adv...,2015.0,NaN,NaN,NaN,A young teenage girl and the ghost of a dead m...,False,False,False,False,False,False,False,False,True
20802,Cryptic,https://www.imdb.com/title/tt10964974/?ref_=ad...,2020.0,NaN,NaN,NaN,Kidnapped by an insane man and dragged into a ...,False,False,False,False,False,False,False,False,True

3. Guardar el dataframe en formato Excel y después crear un dataframe con el Excel. ¿El dataframe es similar al que teníais antes?

In [ ]:
videogames_updated.to_excel("videogames_updated.xlsx", index=False)

In [ ]:
videogames_excel = pd.read_excel("videogames_updated.xlsx")
videogames_excel

,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20798,"Enjoy Your Power, Enjoy Your Choice",https://www.imdb.com/title/tt3845606/?ref_=adv...,2014.0,NaN,NaN,NaN,Add a Plot,False,False,False,False,False,False,False,False,True
20799,RedSun2020,https://www.imdb.com/title/tt0790739/?ref_=adv...,2004.0,NaN,NaN,NaN,Joseph gets kidnapped and it's the player's jo...,False,False,False,False,False,False,False,False,True
20800,Shutter,https://www.imdb.com/title/tt5119948/?ref_=adv...,2015.0,NaN,NaN,NaN,A tech support man who uses a drone to investi...,False,False,False,False,False,False,False,False,True
20801,The Music Machine,https://www.imdb.com/title/tt5142082/?ref_=adv...,2015.0,NaN,NaN,NaN,A young teenage girl and the ghost of a dead m...,False,False,False,False,False,False,False,False,True
20802,Cryptic,https://www.imdb.com/title/tt10964974/?ref_=ad...,2020.0,NaN,NaN,NaN,Kidnapped by an insane man and dragged into a ...,False,False,False,False,False,False,False,False,True

In [7]:
videogames_updated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20803 entries, 0 to 20802
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         20803 non-null  object
 1   url          20803 non-null  object
 2   year         20536 non-null  float64
 3   certificate  7903 non-null   object
 4   rating       11600 non-null  float64
 5   votes        11600 non-null  object
 6   plot         20803 non-null  object
 7   Action       20803 non-null  bool
 8   Adventure    20803 non-null  bool
 9   Comedy       20803 non-null  bool
 10  Crime        20803 non-null  bool
 11  Family       20803 non-null  bool
 12  Fantasy      20803 non-null  bool
 13  Mystery      20803 non-null  bool
 14  Sci-Fi       20803 non-null  bool
 15  Thriller     20803 non-null  bool
dtypes: bool(9), float64(2), object(5)
memory usage: 1.3+ MB

In [ ]:
videogames_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20803 entries, 0 to 20802
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         20803 non-null  object
 1   url          20803 non-null  object
 2   year         20536 non-null  float64
 3   certificate  7903 non-null   object
 4   rating       11600 non-null  float64
 5   votes        11600 non-null  object
 6   plot         20803 non-null  object
 7   Action       20803 non-null  bool
 8   Adventure    20803 non-null  bool
 9   Comedy       20803 non-null  bool
 10  Crime        20803 non-null  bool
 11  Family       20803 non-null  bool
 12  Fantasy      20803 non-null  bool
 13  Mystery      20803 non-null  bool
 14  Sci-Fi       20803 non-null  bool
 15  Thriller     20803 non-null  bool
dtypes: bool(9), float64(2), object(5)
memory usage: 1.3+ MB

4. Crear una carpeta llamada Files y guardar el mismo archivo en esa carpeta en formato csv .

In [ ]:
videogames_csv = videogames_excel.to_csv("./Files/videogames_updated.xlsx")
# Si hay que crear un archivo en una localización específica, se debe indicar la ruta completa al guardarlo (donde indicas el nombre)

5. Copia el archivo personal.json en la carpeta Files.

6. Abre el fichero json (con el json.load(f)) y haz las modificaciones necesarias para que tenga formato de tabla (Para esto necesitas normalizar los datos con el pd.json_normalize).

In [ ]:
import json
import pandas as pd

with open('./Files/personal.json', 'r', encoding='utf-8') as f:
    datos = json.load(f)

# Normalizar los datos
df_personal = pd.json_normalize(datos["workers"]) 
#se debe especificar la clave principal del JSON, que en este caso sería "workers"

In [29]:
df_personal_modificado = df_personal.to_json("./Files/personal_modificado.json")

7. Guardar el json modificado y abrirlo en Pandas.¿Cómo queda ahora?

In [31]:
df_personal

  nombre  edad  experiencia   nivel  salario mascota
0    Ana    34            5  Senior    50000   gatos
1    Eva    37            2     Mid    35000     NaN
2  Marta    27            1  Junior    25000     NaN
3  Paula    30            3     Mid    35000     NaN